version: '2'
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
services:
  db-chat:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: password123
      MYSQL_DATABASE: phonexa_chat
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
  web-chat:
    image: nginx
    restart: always
    ports:
      - "88:88"
    volumes:
      - ${PWD}/../:/app
      - ./nginx/sites/local.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/local.default.conf:/etc/nginx/local.default.conf
    links:
      - php-chat
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8
  php-chat:
    extends:
      file: base-php/base-php.yml
      service: base-php
    restart: always
    working_dir: /app
    volumes:
      - ${PWD}/../:/app
    links:
      - db-chat
      - memcached-chat
    networks:
      vpcbr:
        ipv4_address: 10.5.0.9
  memcached-chat:
    image: memcached:1.5.3-alpine
    restart: always
    command: "memcached -p 11211 -m 2048 -c 8092"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.11
